image:
  azuredisk:
    repository: mcr.microsoft.com/k8s/csi/azuredisk-csi
    tag: latest
    pullPolicy: IfNotPresent
  csiProvisioner:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner
    tag: v2.0.4
    pullPolicy: IfNotPresent
  csiAttacher:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-attacher
    tag: v2.2.0
    pullPolicy: IfNotPresent
  csiResizer:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-resizer
    tag: v0.5.0
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
    tag: v2.0.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
    tag: v2.0.1
    pullPolicy: IfNotPresent

serviceAccount:
  create: true

rbac:
  create: true

controller:
  replicas: 2
  metricsPort: 29604
  runOnMaster: false

node:
  metricsPort: 29605
  
snapshot:
  enabled: false
  image:
    csiSnapshotter:
      repository: mcr.microsoft.com/oss/kubernetes-csi/csi-snapshotter
      tag: v2.0.1
      pullPolicy: IfNotPresent
    csiSnapshotController:
      repository: mcr.microsoft.com/oss/kubernetes-csi/snapshot-controller
      tag: v2.1.1
      pullPolicy: IfNotPresent
  snapshotController:
    replicas: 1
    serviceAccount: true
    rbac: true

linux:
  enabled: true

windows:
  enabled: true
  image:
    livenessProbe:
      repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
      tag: v2.0.1-alpha.1-windows-1809-amd64
      pullPolicy: IfNotPresent
    nodeDriverRegistrar:
      repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
      tag: v2.0.1
      pullPolicy: IfNotPresent
